development:
  adapter: postgresql
  encoding: unicode
  database: airbng
  pool: 2

production:
  adapter: postgresql
  encoding: unicode
  database: airbng
  pool: 2
  
test:
  adapter: postgresql
  encoding: unicode
  database: airbng_test
  pool: 2